// Code generated by goctl. DO NOT EDIT.
package types

type AuthenticationRequest struct {
	Token     string `header:"Token,optional"`
	ValidPath string `header:"ValidPath,optional"`
}

type AuthenticationResponse struct {
	UserID int64 `json:"userID"`
	Role   int   `json:"role"`
}

type LoginRequest struct {
	Username string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type OpenLoginRequest struct {
	Code string `json:"code"` //验证码
	Flag string `json:"flag"` //登录的标志
}

type OpenLoginResponse struct {
	Name string `json:"name"`
	Ican string `json:"ican"`
	Href string `json:"href"` //跳转地址
}

type RegisterRequest struct {
	Username string `json:"nickname"`
	Pwd      string `json:"pwd"`
}

type RegisterResponse struct {
}
